# Generated by deploy/scripts/init-local.sh — do not edit manually.
# Re-generate with: ./deploy/scripts/init-local.sh
{
  domain = "nixflix.zenspider.net";
  acmeEmail = "admin@zenspider.net";
  diskDevice = "/dev/disk/by-id/ata-TOSHIBA_MG04ACA200EY_873OK06BF7QB";
  serverIp = "135.181.79.237";
  sshKeys = [
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCzZGTBWguDPyAO0aCVYGLpXH7seX6/SdknVgnOFruNZXbnhkFenH2zEQ0aOIODKOnyR8YpQsay8wTs1v1H1eEtdWBwac5L7C32YFt3zm0JeLAhjUHbpeH57vNw2eMOgUgDef/x9vE5VZu9WZ3Nyf+0FOTo5R6+posFeRKH01fpTgMUAu2+HNpuJrjHnmEbE2llvbgZ7OzBiFuf1VvsUbYHSXt8O3wb+8cSF6w4oSwX2buV8YWsKR2Hg6bHFTjQR1x81+/qhR4g3TwpmyTcbYEfqHCUBfaSfXyyPxW0Okul3LqcOGVcczFzB2CcoGskjBF995HTOiBaAIh7/xl2b98AXCONAN7Pbj7nTwczx6b2Nbu2qg+y45ELlNPY+gUiSp8qFR4uoYEHhBkj2j9/DtLH+0q21BGXD6clVfVBA8A+LtgSOWn4c94bKfs/LglzzCnXHLlnSgT88KBXPHOSXup8TENDZJjuV2K0jqyihq9dRaGqB/pctc88dgbA1JFnD7TbC5an0A9aGJ5UfkFoDja2Zqe3DmJwzlIf53wJrBhdUhLFSpiBZvYBRvjtZJiqoiwC72G6edhIqbwCiSJs8NumDVsI2DVsQX1a4/6cEmzGRs85ZITd5qab9yHTuywoJQ5nwCib1ICsyTcq15RaKud7ryfMAfH2e7ui4Rt2rQgfew== cardno:000608752971"
  ];
}
