#!/usr/bin/env bash
# deploy/scripts/init-local.sh
#
# Decrypts deploy/secrets/local.yaml and generates deploy/local.nix.
# Run this once after cloning on a new machine, or after rotating secrets.
#
# Requires: sops, age private key accessible to sops
#
# Usage:
#   ./deploy/scripts/init-local.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SECRETS="$REPO_ROOT/deploy/secrets/local.yaml"
OUTPUT="$REPO_ROOT/deploy/local.nix"

if [ ! -f "$SECRETS" ]; then
  echo "ERROR: $SECRETS not found" >&2
  exit 1
fi

echo "Decrypting deploy/secrets/local.yaml..."

DOMAIN=$(sops --decrypt --extract '["domain"]' "$SECRETS")
ACME_EMAIL=$(sops --decrypt --extract '["acme_email"]' "$SECRETS")
DISK_DEVICE=$(sops --decrypt --extract '["disk_device"]' "$SECRETS")
SERVER_IP=$(sops --decrypt --extract '["server_ip"]' "$SECRETS")
SSH_KEY=$(sops --decrypt --extract '["ssh_keys"]' "$SECRETS")

cat > "$OUTPUT" << NIXEOF
# Generated by deploy/scripts/init-local.sh — do not edit manually.
# Re-generate with: ./deploy/scripts/init-local.sh
{
  domain = "${DOMAIN}";
  acmeEmail = "${ACME_EMAIL}";
  diskDevice = "${DISK_DEVICE}";
  serverIp = "${SERVER_IP}";
  sshKeys = [
    "${SSH_KEY}"
  ];
}
NIXEOF

echo "Generated deploy/local.nix"

# Tell git to ignore local changes to this file so it never accidentally
# appears in git status or gets committed with real values.
git -C "$REPO_ROOT" update-index --skip-worktree deploy/local.nix
echo "Marked deploy/local.nix as skip-worktree (git will ignore local changes)"
