jellyfin_admin_password: ENC[AES256_GCM,data:+7cn1+NaAwXsCQ==,iv:ltUeIbGPq0B8u7fWZ4/UpG8ab7WhzbA1gPeF/6mIp3A=,tag:sRcFC+sGm01IsrbCNL/Xaw==,type:str]
jellyseerr_admin_password: ENC[AES256_GCM,data:f1JNYkVrYu8q9w==,iv:iW/CmeP7d4zK+45+YShJmEec6qTgzMdoboo4FLdk3ls=,tag:JoM6YCEE4VO5DOunGy9slA==,type:str]
sabnzbd_api_key: ENC[AES256_GCM,data:jwCjMiBX2DKBifKAf8Ry8DVwR4uP2e7r5gSHPQWEqYw=,iv:WkTN6fPa1V8YurI0gm5A95CvfdGd192Eh6MBvMGbks0=,tag:W8RwM6oE7YyZE4Y3wy4HIw==,type:str]
qbittorrent_password: ENC[AES256_GCM,data:3a3zhARJKap0xw==,iv:P5n/Jmfsme0KiIUW6zGK7GAGef36OCftxKFy7xlC31k=,tag:Y8NoJaGAqEmTgOeNix5ovg==,type:str]
sops:
    age:
        - recipient: age1dpytxdj0d2pza45ganrc0xmlggf9clllal9ey0yatfyc92fze33sx64dup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSG9mclFodmVRZk00enBP
            TmE3NmtnQnlGd0VxRzNiSTVIWEtOR1VqMW1BCnRwaFlyUWNrZjU4cnE2S0Q2QnVw
            UjZJNHVNUEdWZFJhTzhWUmJKMGJVYWsKLS0tIC9wS3U1MGQya0s4RVB4ejgreGFO
            VnBodHM3NHRlc1pBUjZIVE9lSURmSHcKVtz7czlNcT4tOenYC+tAr2bj13pOqV1J
            1+G14KiorjaF5Zz0zurVSOtwVTYJfmniNnAPJmjokbuamGlg1O+5CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T18:57:59Z"
    mac: ENC[AES256_GCM,data:m/ngHs8LKFN2cjXrBhQU2STV7sOaTU3FaTFFdk4HKPhYtMfUsqjtXvGxoipzxHvYILrXhPG7ZuLqkhBeHrV2nkZ0YRyMx0UNCi2/z8wEjeiH5HSjCV0KJ9lBrAG/QYoI+8VSg7nmoohyC6amWDvHVFcSOa3uOeTJ6z1EmrLbQrM=,iv:X/fYXseJcT8EmD27PIDKepmGw7c7UnGuLW9gmB6uEOY=,tag:YudLJxQmWHHJ/KHzDjwWhA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
