jellyfin_admin_password: ENC[AES256_GCM,data:VMmSVR+5xZg=,iv:+pfdHdNNs8fB6idTDrBJ3HZ4kzFpM+u9ghb3mXkRrIc=,tag:HvHOHy8Rk23WiOD49mNcLw==,type:str]
jellyseerr_admin_password: ENC[AES256_GCM,data:rIqXlPgYpEE=,iv:0OIP8OM5SA386Hu7NWuZnbcnKmErvzaHfaRkzX1yA9Y=,tag:YKwOxKhERy2OV3gh3jWUyA==,type:str]
sabnzbd_api_key: ENC[AES256_GCM,data:jwCjMiBX2DKBifKAf8Ry8DVwR4uP2e7r5gSHPQWEqYw=,iv:WkTN6fPa1V8YurI0gm5A95CvfdGd192Eh6MBvMGbks0=,tag:W8RwM6oE7YyZE4Y3wy4HIw==,type:str]
sops:
    age:
        - recipient: age1dpytxdj0d2pza45ganrc0xmlggf9clllal9ey0yatfyc92fze33sx64dup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSG9mclFodmVRZk00enBP
            TmE3NmtnQnlGd0VxRzNiSTVIWEtOR1VqMW1BCnRwaFlyUWNrZjU4cnE2S0Q2QnVw
            UjZJNHVNUEdWZFJhTzhWUmJKMGJVYWsKLS0tIC9wS3U1MGQya0s4RVB4ejgreGFO
            VnBodHM3NHRlc1pBUjZIVE9lSURmSHcKVtz7czlNcT4tOenYC+tAr2bj13pOqV1J
            1+G14KiorjaF5Zz0zurVSOtwVTYJfmniNnAPJmjokbuamGlg1O+5CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T17:36:34Z"
    mac: ENC[AES256_GCM,data:zBTT9xjsd4P6p7A57DzUpoe8NiD91ucxoWd+9ESdKAlwZBMM9eX4sx/NpCw9V4RaJrH2x5jyvQlmScKxL6/wMkDUaEwzOTn0lX0gfapBQKDpNGUthR5aYJwDKOjXxoHjNh9DnytHxHilyWXC8gx00qI7iUrVIcKSxt6oJmHwIgs=,iv:wCiY83NFBLJoVYGu5lUcJZkPZzzSlPj8SCO/LxNpX7g=,tag:fyvbzKduTMNvTz9C0Q9cXA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
