sonarr_api_key: ENC[AES256_GCM,data:Om/VWmabdlw5qcLUWGh/IVcdC9uYsVD1x29PcvXKSoE=,iv:oHKAmW9dJwCv6z1JiduEArO5FeigX5BeJnpwbMJTrY0=,tag:XZUhXd+wS9B8vzj6yljRhA==,type:str]
sonarr_anime_api_key: ENC[AES256_GCM,data:/GnWCOgjrrMJd+UIgaVdn1aDaq5jg4sLrRF+LyGfydY=,iv:MotciW+kz1Pim48ag1UgLWJRyhWyMmm/Gq9FrZxh+wo=,tag:ZMvDgqDQOkkdXjrz7KZKLg==,type:str]
radarr_api_key: ENC[AES256_GCM,data:OQlHRFysbKDt7syaMEEEn/J0s2Zs3YoXAyP4E0BlRss=,iv:BHJ46u5Fv/6+qBA6riyJAepLoQxsZwV5ut8SxAVLBHg=,tag:ybK4aPi8KOYMaruSXtNZBA==,type:str]
prowlarr_api_key: ENC[AES256_GCM,data:gYdTy3gCp0xNVDY+6BHuNpmMFEwRXF9BfwURDx/AyJY=,iv:L2OBTi85GSA2oSgqO0QbZo2qm0G/lngHohoIP79cMJE=,tag:alAhmQ3aVEtGId+4QiiZ7w==,type:str]
lidarr_api_key: ENC[AES256_GCM,data:CMU2okU7eAhu/GeHJoUtIho7SbUo8GJ0+RwsMo7sFgw=,iv:zfx+w5TY8F3OJqK2JmzbH63QXwtJq3lbRxkb8TxXRFw=,tag:gEw3JVgchjCPtMAODXBJvw==,type:str]
sops:
    age:
        - recipient: age1dpytxdj0d2pza45ganrc0xmlggf9clllal9ey0yatfyc92fze33sx64dup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQ0NZNEEybVR2d2tYMWdy
            eFVEeVROajhwR1RaWHplTGNoRDNnY0o5OXdRCmdScGJpci9oMytnVmZFZ1haaHBQ
            QXp0NjFNc1U4SS9VTEh1azkvTlp4Y2cKLS0tIGxwQWY3SHJ2amVoeWdpb2doTVZV
            cmhFNW5QQTRuZkkzY1pUUFc1TjFHRHcKPZxOyelMXqnr4//C95r0vB0/PjQ/3FTh
            KBv5UACwSsQDIc+l85y/4Jxq6UqChGHDMKBI0Wth7Pp6jEeRBdTfVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T17:36:29Z"
    mac: ENC[AES256_GCM,data:Y+DSHE1Tu9OPf3VVauixztrb7ANjYNAHZEb/B+t4/v2hrxduD9NElf/hh7thtff7+mJnzI/arpOhQhOBZa8uNHs9fmhTINcLzfEJt1oy/nbNfH7v+9T7AkVlzBiMIDJNIonk3grkoBeduijHONSdg0nG+fTJbahWwhguAzSI/jk=,iv:c7x2x3JJeCQuEKFMpADk4MBnc0dea7JW2lxKHU6J7Us=,tag:AEvNbg0OVA9VG1R0B5gHKg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
