account_number: ENC[AES256_GCM,data:HZHx8Hw0ZEH9M1xs,iv:iRnfpH5W8RV+bikjYrYAoYgq2uClTc+RWhN5bJz8U9s=,tag:eARN7QqnkisSVpveru+bqQ==,type:str]
sops:
    age:
        - recipient: age1dpytxdj0d2pza45ganrc0xmlggf9clllal9ey0yatfyc92fze33sx64dup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbk9MTGRIWEx0WmY2K2xN
            N01ZRlRGVU5Ua1RVVFUwbW9QUFNWY1Q0L1VNClRWT2ZsdkxXTU5nWFNzYXBmK1Y0
            UDdneHZ2bGVaMmxQSGdURXQyWUlWRXcKLS0tIENhUEJLYlpXUkNweXVPaGNFSDM3
            blBFK2haRUV0YmRVakMzTWpFbGdGSkEKideBonYFnPLeN8VuR0l7k/t1GzBIWaqT
            bqbboNQIPPCKQWwhTAVUa2ZMg3EXrS6yppT7W2tzKdboX3WdUVWhWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T18:49:14Z"
    mac: ENC[AES256_GCM,data:5UBulXTpsB1fxO9eBCLvE2eQD63yyQ16K9hpAMl5Bm3W3F3zNCWcg4p/dZNveDBAGTtNsbt7iCFf4zfqmCcU8zzjzNYh1FKXo2cyfd+BdK1oO4qn0mj5TGZKu16zQ45VTzFhhgnvNWuaFENghw3t0+tJDuZV+w2O9l/OtEzZc5c=,iv:MSd2RAmj+QVQIc0aoRo6KWUyCezFpok67f5BKJb5s9o=,tag:VXTwHxh0jPCykJtKPMk1/Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
